version: "3.10"

services:
  django:
    container_name: hakka-cake
    build:
      context: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - 8000:8000
