# Generated by Django 4.2.5 on 2023-10-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_jwt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/'),
        ),
    ]
