# Generated by Django 4.2.5 on 2023-10-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_jwt', '0004_alter_staff_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_delete_client',
            field=models.BooleanField(default=False),
        ),
    ]
